"""Handles the MEDS form.

This is a UDS-specific form in V3 and earlier that provides the drugs
data. Must correspond to an UDS visit. This is mainly used to inform UDS
A4 NACC derived variables.
"""

import csv
import datetime
from importlib import resources
from typing import Dict, List

from nacc_attribute_deriver import config
from nacc_attribute_deriver.attributes.collection.attribute_collection import (
    AttributeCollection,
)
from nacc_attribute_deriver.attributes.namespace.namespace import (
    BaseNamespace,
)
from nacc_attribute_deriver.symbol_table import SymbolTable
from nacc_attribute_deriver.utils.date import date_from_form_date
from nacc_attribute_deriver.utils.errors import (
    AttributeDeriverError,
    InvalidFieldError,
)

# hardcoded replacement mappings
REPLACEMENT_DRUGS = {"s10008": "d04523", "s10136": "d04523"}


def load_v1_drugs() -> Dict[str, str | None]:
    """Load the V1 drugs list. Done globally so it's only done once per
    execution.

    In UDS V1 all the drugs were written in. Uses drug_ids_v1.csv, which
    was manually generated by comparing the raw values with expected QAF
    values. The list itself is imperfect/mappings are debatable but
    really just designed to produce the same drugs list as the legacy
    system.
    """
    drugs_file_v1 = resources.files(config).joinpath("drug_ids_v1.csv")
    drugs: Dict[str, str | None] = {}

    with drugs_file_v1.open("r") as fh:
        reader = csv.DictReader(fh)
        # map raw drug names to drug IDs
        for row in reader:
            raw_drug = row["raw_drug"].strip().lower()
            drug_id = row["drug_id"].strip().lower()
            drugs[raw_drug] = drug_id

    return drugs


# load this globally so it's only done once per execution
DRUGS_V1 = load_v1_drugs()


class MEDSFormAttributeCollection(AttributeCollection):
    def __init__(self, table: SymbolTable) -> None:
        """Initializer."""
        self.__meds = BaseNamespace(
            table=table,
            attribute_prefix="file.info.forms.json",
            required=frozenset(["module", "formver"]),
        )
        module = self.__meds.get_required("module", str)
        if module.upper() != "MEDS":
            raise InvalidFieldError(
                f"Current file is not a MEDS form: found {module}",
            )

        self.__formver = self.__meds.get_value("formver", float)

        # ideally we externally link MEDS to UDS file by UDS visitdate
        self.__visitdate = date_from_form_date(table.get("_uds_visitdate", None))

        # if no uds_visitdate, fall back to frmdatea4
        if not self.__visitdate:
            date_attribute = (
                "frmdatea4" if (self.__formver and self.__formver < 2) else "frmdatea4g"
            )
            formdate = self.__meds.get_value(date_attribute, str)
            self.__visitdate = date_from_form_date(formdate)

        if not self.__visitdate:
            raise AttributeDeriverError("Cannot determine MEDS form date")

    def get_date(self) -> datetime.date:
        """Get the corresponding UDS visitdate."""
        if not self.__visitdate:
            raise AttributeDeriverError("No MEDS date set")

        return self.__visitdate

    def _create_drugs_list(self) -> List[str]:
        """Returns list of drugs for this visit."""
        drugs = []

        # in V1, each prescription medication is specified by variables
        # PMA - PMT, need to extract
        if self.__formver == 1:
            drugs = self.__get_v1_drugs()
        else:
            drugs_str = self.__meds.get_value("drugs_list", str)
            if drugs_str:
                drugs = [x.strip().lower() for x in drugs_str.split(",")]

        # perform replacements as needed
        for i, drug in enumerate(drugs):
            if drug in REPLACEMENT_DRUGS:
                drugs[i] = REPLACEMENT_DRUGS[drug]

        return sorted(drugs)

    def __get_v1_drugs(self) -> List[str]:
        """Gets V1 drugs by mapping write-ins to normalized DB."""
        # if not in drugs_db, use drug_name
        drugs_list = []
        for i in range(ord("a"), ord("t") + 1):
            # pm = prescription medication
            # nm = non-presscription medication (over the counter)
            # vs = vitamin/supplement
            for prefix in ["pm", "nm", "vs"]:
                drug_name = self.__meds.get_value(f"{prefix}{chr(i)}", str)
                if not drug_name:
                    continue

                drug_name = drug_name.strip().lower()
                drug_id = DRUGS_V1.get(drug_name, "xxxxxx")
                drugs_list.append(drug_id if drug_id is not None else drug_name)

        return drugs_list
